<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>de.fraunhofer.iese.mydata</groupId>
    <artifactId>parent</artifactId>
    <version>5.0.0-SNAPSHOT</version>
    <relativePath>./mydata-parent/pom.xml</relativePath>
  </parent>

  <artifactId>base</artifactId>
  <packaging>pom</packaging>

  <name>${project.groupId}:${project.artifactId}</name>
  <description>MYDATA :: Base project containing all projects</description>

  <properties>
    <central-publishing-maven-plugin.version>0.11.0</central-publishing-maven-plugin.version>
  </properties>

  <modules>
    <module>mydata-parent</module>
    <module>core</module>
    <module>connectors-rest</module>
    <module>pdp</module>
    <module>sdk</module>
    <module>sdk-spring</module>
  </modules>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.sonatype.central</groupId>
          <artifactId>central-publishing-maven-plugin</artifactId>
          <version>${central-publishing-maven-plugin.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

  <profiles>
    <profile>
      <id>coverage</id>
      <dependencies>
        <dependency>
          <groupId>de.fraunhofer.iese.mydata</groupId>
          <artifactId>core</artifactId>
        </dependency>
        <dependency>
          <groupId>de.fraunhofer.iese.mydata</groupId>
          <artifactId>connectors.rest</artifactId>
        </dependency>
        <dependency>
          <groupId>de.fraunhofer.iese.mydata</groupId>
          <artifactId>pdp</artifactId>
        </dependency>
        <dependency>
          <groupId>de.fraunhofer.iese.mydata</groupId>
          <artifactId>sdk</artifactId>
        </dependency>
        <dependency>
          <groupId>de.fraunhofer.iese.mydata</groupId>
          <artifactId>sdk.spring</artifactId>
        </dependency>
      </dependencies>
      <build>
        <plugins>
          <plugin>
            <groupId>org.jacoco</groupId>
            <artifactId>jacoco-maven-plugin</artifactId>
            <executions>
              <execution>
                <phase>verify</phase>
                <goals>
                  <goal>report-aggregate</goal>
                </goals>
                <configuration>
                  <dataFileIncludes>
                    <dataFileInclude>target/jacoco.exec</dataFileInclude>
                  </dataFileIncludes>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>publish</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.sonatype.central</groupId>
            <artifactId>central-publishing-maven-plugin</artifactId>
            <extensions>true</extensions>
            <configuration>
              <autoPublish>true</autoPublish>
              <deploymentName>MYDATA - ${project.version}</deploymentName>
              <excludeArtifacts>base</excludeArtifacts>
              <publishingServerId>maven-central</publishingServerId>
              <waitUntil>published</waitUntil>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

</project>
