<!--
=================================LICENSE_START=================================
MYDATA Control Technologies

Copyright (C) 2016 - present Fraunhofer-Gesellschaft zur Foerderung der
angewandten Forschung e.V. acting on behalf of its Fraunhofer Institute
for Experimental Software Engineering (IESE)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=================================LICENSE_END===================================
-->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.mydata-control.de/4.0/mydataLanguage"
	xmlns:tns="http://www.mydata-control.de/4.0/mydataLanguage"
	xmlns:parameter="http://www.mydata-control.de/4.0/parameter"
	xmlns:constant="http://www.mydata-control.de/4.0/constant"
	xmlns:event="http://www.mydata-control.de/4.0/event"
	xmlns:pip="http://www.mydata-control.de/4.0/pip"
	xmlns:variable="http://www.mydata-control.de/4.0/variable"
	xmlns:variableDeclaration="http://www.mydata-control.de/4.0/variableDeclaration"
	xmlns:valueChanged="http://www.mydata-control.de/4.0/valueChanged"
	elementFormDefault="qualified"> 

	<import namespace="http://www.mydata-control.de/4.0/parameter"
		schemaLocation="mydataParameter.xsd" />
	<import namespace="http://www.mydata-control.de/4.0/constant"
		schemaLocation="mydataConstant.xsd" />
	<import namespace="http://www.mydata-control.de/4.0/event"
		schemaLocation="mydataEvent.xsd" />
	<import namespace="http://www.mydata-control.de/4.0/pip"
		schemaLocation="mydataPIP.xsd" />
	<import namespace="http://www.mydata-control.de/4.0/variable"
		schemaLocation="mydataVariable.xsd" />
	<import
		namespace="http://www.mydata-control.de/4.0/variableDeclaration"
		schemaLocation="mydataVariableDeclaration.xsd" />
	<import namespace="http://www.mydata-control.de/4.0/valueChanged"
		schemaLocation="mydataValueChanged.xsd" />



	<!-- Groups -->
	<group name="FunctionGroup">
		<choice>
			<group ref="tns:BooleanFunctionGroup" />
			<group ref="tns:NumberFunctionGroup" />
			<group ref="tns:StringFunctionGroup" />
		</choice>
	</group>

	<group name="BooleanFunctionGroup">
		<choice>
			<element name="less" type="tns:FunctionNumberType" />
			<element name="lessEqual" type="tns:FunctionNumberType" />
			<element name="greater" type="tns:FunctionNumberType" />
			<element name="greaterEqual" type="tns:FunctionNumberType" />
			<element name="equals" type="tns:FunctionEqualsType" />
			<element name="eventHasParameter" type="tns:FunctionEventHasParameterType" />
			<element name="regex" type="tns:FunctionRegexType" />
			<element name="contains" type="tns:FunctionContainsType" />
			<element name="and" type="tns:FunctionAndType" />
			<element name="or" type="tns:FunctionOrType" />
			<element name="not" type="tns:FunctionNotType" />
			<element name="xor" type="tns:FunctionXorType" />
			<element name="implies" type="tns:FunctionImpliesType" />
			<group ref="valueChanged:ValueChangedGroup" />
			<element name="execute" type="tns:FunctionExecuteType" />
			<element name="continuousOccurrence" type="tns:FunctionContinuousOccurrenceType" />
			<element name="time" type="tns:PolicyTimeType" />
			<element name="date" type="tns:PolicyDateType" />
			<element name="day" type="tns:PolicyDayType" />
		</choice>
	</group>

	<complexType name="PolicyTimeType">
		<attribute name="is" type="string" use="required" />
		<attribute name="value" use="required">
			<simpleType>
				<restriction base="string">
					<pattern value="([0-9]|0[0-9]|1[0-9]|2[0-3]):([0-5][0-9])" />
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<complexType name="PolicyDateType">
		<attribute name="is" type="string" use="required" />
		<attribute name="value" use="required">
			<simpleType>
				<restriction base="string">
					<pattern value="(0[1-9]|1\d|2\d|3[01])\.(0[1-9]|1[0-2])\.(19|20)\d{2}" />
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<complexType name="PolicyDayType">
		<attribute name="value" type="string" use="required" />
	</complexType>

	<group name="NumberFunctionGroup">
		<choice>
			<element name="size" type="tns:FunctionSizeType" />
			<element name="plus" type="tns:FunctionNumberType" />
			<element name="minus" type="tns:FunctionNumberType" />
			<element name="multiply" type="tns:FunctionNumberType" />
			<element name="divide" type="tns:FunctionNumberType" />
			<element name="count" type="tns:FunctionCountType" />
		</choice>
	</group>

	<group name="StringFunctionGroup">
		<choice>
			<element name="concat" type="tns:FunctionConcatType" />
		</choice>
	</group>

	<group name="StringGroup">
		<choice>
			<group ref="event:eventGroup" />
			<group ref="pip:pipGroup" />
			<group ref="tns:FunctionGroup" />
			<group ref="constant:ConstantGroup" />
			<element ref="variable:string" />
		</choice>
	</group>

	<group name="BooleanGroup">
		<choice>
			<element ref="constant:true" />
			<element ref="constant:false" />
			<element ref="pip:boolean" />
			<element ref="event:boolean" />
			<element ref="variable:boolean" />
			<group ref="tns:BooleanFunctionGroup" />
		</choice>
	</group>

	<group name="NumberGroup">
		<choice>
			<element ref="constant:number" />
			<element ref="pip:number" />
			<element ref="event:number" />
			<element ref="variable:number" />
			<group ref="tns:NumberFunctionGroup" />
		</choice>
	</group>

	<!-- Function -->

	<complexType name="PointInTimeType">
		<sequence>
			<element name="eventOccurrence" type="tns:EventOccurrenceType"
				minOccurs="0" maxOccurs="1" />
		</sequence>
		<attribute name="time" use="optional">
			<simpleType>
				<restriction base="string">
					<pattern
						value="([+-]?0?[1-9]|[12][0-9]|3[01]|\*)\.([+-]?0?[1-9]|1[012]|\*)\.((19|20)\d\d|\*|[+-]\d{1,3}) ([+-]?[0-9]|0[0-9]|1[0-9]|2[0-3]|\*):([0-5][0-9]|\*|[+-][0-5]?[0-9]):([0-5][0-9]|\*|[+-][0-5]?[0-9])" />
				</restriction>
			</simpleType>
		</attribute>
	</complexType>


	<complexType name="WhenTimeType">
		<sequence>
			<element name="start" type="tns:PointInTimeType" minOccurs="0"
				maxOccurs="1" />
			<element name="end" type="tns:PointInTimeType" minOccurs="0"
				maxOccurs="1" />
		</sequence>
		<attribute name="fixedTime" type="tns:FixedTime" use="optional" />
	</complexType>



	<complexType name="EventOccurrenceType">
		<sequence minOccurs="0" maxOccurs="unbounded">
			<group ref="parameter:ParamTypeGroup" />
		</sequence>
		<attribute name="event" use="required">
			<simpleType>
				<restriction base="string">
					<pattern value="urn:action:[a-z0-9\-_\\.]+:[a-zA-Z0-9\-_\\.]+"/>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="mode" type="tns:EventOccurrenceModeType"
			use="optional" />
	</complexType>

	<complexType name="FunctionContinuousOccurrenceType">
		<complexContent>
			<extension base="tns:FunctionCountType">
				<attribute name="interval" use="required">
					<simpleType>
						<restriction base="string">
							<pattern
								value="(([0-9]+y)?([0-9]+w)?([0-9]+d)?([0-9]+h)?([0-9]+m)?([0-9]+s)?)" />
						</restriction>
					</simpleType>
				</attribute>
				<attribute name="minOccurrences" type="integer" use="optional" />
				<attribute name="maxOccurrences" type="integer" use="optional" />
			</extension>
		</complexContent>
	</complexType>

	<complexType name="FunctionCountType">
		<sequence>
			<element name="eventOccurrence" type="tns:EventOccurrenceType" />
			<choice minOccurs="1" maxOccurs="1">
				<element name="when" type="tns:WhenTimeType"></element>
			</choice>
		</sequence>
	</complexType>

	<complexType name="FunctionExecuteType">
		<sequence>
			<group ref="parameter:ParamTypeGroup" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="action" use="required">
			<simpleType>
				<restriction base="string">
					<pattern value="urn:action:[a-z0-9\-_\.]+:[a-zA-Z0-9\-_\.]+"></pattern>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<complexType name="FunctionNumberType">
		<sequence>
			<choice minOccurs="2" maxOccurs="unbounded">
				<group ref="tns:NumberGroup" />
			</choice>
		</sequence>
	</complexType>


	<complexType name="FunctionEqualsType">
		<choice minOccurs="2" maxOccurs="unbounded">
			<group ref="event:eventGroup" />
			<group ref="tns:FunctionGroup" />
			<group ref="pip:pipGroup" />
			<group ref="constant:ConstantGroup" />
			<group ref="variable:ReferenceVariableGroup" />
		</choice>
	</complexType>

	<complexType name="FunctionEventHasParameterType">
		<choice minOccurs="1" maxOccurs="unbounded">
			<element ref="event:string" />
			<group ref="tns:StringFunctionGroup" />
			<element ref="pip:string" />
			<element ref="constant:string" />
			<element ref="variable:string" />
		</choice>
		<attribute name="mode" type="tns:MultiFunctionModeType" use="optional"
			default="ALL" />
	</complexType>

	<complexType name="FunctionRegexType">
		<sequence>
			<choice minOccurs="1" maxOccurs="unbounded">
				<element ref="event:string" />
				<group ref="tns:StringFunctionGroup" />
				<element ref="pip:string" />
				<element ref="constant:string" />
				<element ref="variable:string" />
			</choice>
		</sequence>
		<attribute name="regex" type="string" use="required" />
		<attribute name="mode" type="tns:MultiFunctionModeType" use="optional"
			default="ALL" />
	</complexType>

	<!-- <complexType name="FunctionContainsType"> <sequence> <choice minOccurs="2" 
		maxOccurs="unbounded"> <group ref="event:eventGroup" /> <group ref="tns:FunctionGroup" 
		/> <group ref="pip:pipGroup" /> <group ref="constant:ConstantGroup" /> <group 
		ref="variable:ReferenceVariableGroup" /> </choice> </sequence> <attribute 
		name="mode" type="tns:MultiFunctionModeType" use="optional" default="ALL" 
		/> </complexType> -->

	<complexType name="FunctionContainsType">
		<sequence>
			<choice minOccurs="1" maxOccurs="1">
				<element ref="event:list" />
				<element ref="constant:list" />
				<element ref="pip:list" />
				<element ref="parameter:list"/>
				<element ref="variable:list"/>
			</choice>
			<choice minOccurs="1"  maxOccurs="unbounded">
				<group ref="parameter:ParamTypeGroup"></group>
				<group ref="event:eventGroup" />
				<group ref="tns:FunctionGroup" />
				<group ref="pip:pipGroup" />
				<group ref="constant:ConstantGroup" />
				<group ref="variable:ReferenceVariableGroup" />
			</choice>
		</sequence>
		<attribute name="mode" type="tns:MultiFunctionModeType" use="optional"
			default="ALL" />
	</complexType>


	<complexType name="FunctionSizeType">
		<choice minOccurs="1" maxOccurs="unbounded">
			<element ref="event:list" />
			<group ref="tns:StringFunctionGroup" />
			<element ref="pip:string" />
			<element ref="pip:list" />
			<element ref="parameter:list" />
			<element ref="variable:list" />
		</choice>
	</complexType>

	<complexType name="FunctionConcatType">
		<choice minOccurs="1" maxOccurs="unbounded">
			<group ref="event:eventGroup" />
			<group ref="tns:FunctionGroup" />
			<group ref="pip:pipGroup" />
			<group ref="constant:ConstantGroup" />
			<group ref="variable:ReferenceVariableGroup" />
		</choice>
	</complexType>

	<complexType name="FunctionNotType">
		<choice minOccurs="1" maxOccurs="1">
			<group ref="tns:BooleanFunctionGroup" />
			<element ref="pip:boolean" />
			<element ref="constant:true" />
			<element ref="constant:false" />
			<element ref="event:boolean" />
			<element ref="variable:boolean" />
		</choice>
	</complexType>

	<complexType name="FunctionAndType">
		<choice minOccurs="1" maxOccurs="unbounded">
			<group ref="tns:BooleanFunctionGroup" />
			<element ref="pip:boolean" />
			<element ref="constant:true" />
			<element ref="constant:false" />
			<element ref="event:boolean" />
			<element ref="variable:boolean" />
		</choice>
		<attribute name="mode" type="tns:FunctionEvaluationType"
			use="optional" default="LAZY" />
	</complexType>

	<complexType name="FunctionOrType">
		<choice minOccurs="1" maxOccurs="unbounded">
			<group ref="tns:BooleanFunctionGroup" />
			<element ref="pip:boolean" />
			<element ref="constant:true" />
			<element ref="constant:false" />
			<element ref="event:boolean" />
			<element ref="variable:boolean" />
		</choice>
		<attribute name="mode" type="tns:FunctionEvaluationType"
			use="optional" default="LAZY" />
	</complexType>

	<complexType name="FunctionXorType">
		<choice minOccurs="1" maxOccurs="unbounded">
			<group ref="tns:BooleanFunctionGroup" />
			<element ref="pip:boolean" />
			<element ref="constant:true" />
			<element ref="constant:false" />
			<element ref="event:boolean" />
			<element ref="variable:boolean" />
		</choice>
		<attribute name="mode" type="tns:FunctionEvaluationType"
			use="optional" default="LAZY" />
	</complexType>

	<complexType name="FunctionImpliesType">
		<choice minOccurs="2" maxOccurs="2">
			<group ref="tns:BooleanFunctionGroup" />
			<element ref="pip:boolean" />
			<element ref="constant:true" />
			<element ref="constant:false" />
			<element ref="event:boolean" />
			<element ref="variable:boolean" />
		</choice>
		<attribute name="mode" type="tns:FunctionEvaluationType"
			use="optional" default="LAZY" />
	</complexType>

	<simpleType name="MultiFunctionModeType">
		<restriction base="string">
			<enumeration value="ALL" />
			<enumeration value="EXACTLY_ONE" />
			<enumeration value="AT_LEAST_ONE" />
			<enumeration value="NONE" />
		</restriction>
	</simpleType>

	<simpleType name="FunctionEvaluationType">
		<restriction base="string">
			<enumeration value="EAGER" />
			<enumeration value="LAZY" />
		</restriction>
	</simpleType>

	<simpleType name="EventOccurrenceModeType">
		<restriction base="string">
			<enumeration value="FIRST" />
			<enumeration value="LAST" />
		</restriction>
	</simpleType>

	<simpleType name="FixedTime">
		<restriction base="string">
			<enumeration value="always" />
			<enumeration value="thisMinute" />
			<enumeration value="lastMinute" />
			<enumeration value="thisHour" />
			<enumeration value="lastHour" />
			<enumeration value="today" />
			<enumeration value="yesterday" />
			<enumeration value="thisWeek" />
			<enumeration value="lastWeek" />
			<enumeration value="thisSunWeek" />
			<enumeration value="lastSunWeek" />
			<enumeration value="thisMonth" />
			<enumeration value="lastMonth" />
			<enumeration value="thisYear" />
			<enumeration value="lastYear" />
            
		</restriction>
	</simpleType>


	<!-- End of Function -->



	<complexType name="AuthorizationModifyType">
		<sequence>
			<group ref="parameter:ParamTypeGroup" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="eventParameter" type="string" use="required" />
		<attribute name="method" type="string" use="required" />
		<attribute name="jsonPathQuery" type="string" use="optional" />
		<attribute name="reason" type="string" use="optional" />
	</complexType>

	<complexType name="AuthorizationAllowType">
		<attribute name="reason" type="string" use="optional" />
	</complexType>

	<complexType name="AuthorizationInhibitType">
		<attribute name="reason" type="string" use="optional" />
	</complexType>

	<complexType name="DecisionType">
		<sequence minOccurs="1">
			<choice minOccurs="0" maxOccurs="1">
				<element name="allow" type="tns:AuthorizationAllowType" />
				<element name="inhibit" type="tns:AuthorizationInhibitType" />
				<element name="modify" type="tns:AuthorizationModifyType"
					minOccurs="1" maxOccurs="unbounded" />
			</choice>
			<element name="execute" type="tns:FunctionExecuteType"
				minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="IfType">
		<sequence>
			<group ref="tns:BooleanGroup" minOccurs="1" maxOccurs="1" />
			<element name="then" type="tns:DecisionType" minOccurs="1"
				maxOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="MechanismType">
		<sequence>
			<element name="if" type="tns:IfType" minOccurs="1" maxOccurs="1" />
			<element name="elseif" type="tns:IfType" minOccurs="0"
				maxOccurs="unbounded" />
			<element name="else" type="tns:DecisionType" minOccurs="0"
				maxOccurs="1" />
			<element name="execute" type="tns:FunctionExecuteType"
				minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="id" type="ID" use="optional" />
		<attribute name="event" use="required">
			<simpleType>
				<restriction base="string">
					<pattern value="urn:action:[a-z0-9\-_\.]+:[a-zA-Z0-9\-_\.]+"></pattern>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="description" type="string" use="optional" />

	</complexType>



	<complexType name="PolicyType">
		<sequence>
			<group ref="variableDeclaration:variableDeclarationGroup"
				minOccurs="0" maxOccurs="unbounded" />
			<element name="mechanism" type="tns:MechanismType" minOccurs="1"
				maxOccurs="unbounded" />
		</sequence>

		<attribute name="id" use="required">
			<simpleType>
				<restriction base="string">
					<pattern value="urn:policy:[a-z0-9\-_\.]+:[a-zA-Z0-9\-_\.]+"></pattern>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="name" type="string" use="optional" />
		<attribute name="description" type="string" use="optional" />
	</complexType>

	<element name="policy" type="tns:PolicyType" />

</schema>