<!--
=================================LICENSE_START=================================
MYDATA Control Technologies

Copyright (C) 2016 - present Fraunhofer-Gesellschaft zur Foerderung der
angewandten Forschung e.V. acting on behalf of its Fraunhofer Institute
for Experimental Software Engineering (IESE)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=================================LICENSE_END===================================
-->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.mydata-control.de/4.0/valueChanged"
	xmlns:tns="http://www.mydata-control.de/4.0/valueChanged"
	xmlns:language="http://www.mydata-control.de/4.0/mydataLanguage"
	xmlns:pip="http://www.mydata-control.de/4.0/pip"
	xmlns:event="http://www.mydata-control.de/4.0/event"
	xmlns:constant="http://www.mydata-control.de/4.0/constant"
	elementFormDefault="qualified">

	<import namespace="http://www.mydata-control.de/4.0/constant"
		schemaLocation="mydataConstant.xsd" />
	<import namespace="http://www.mydata-control.de/4.0/pip"
		schemaLocation="mydataPIP.xsd" />
	<import namespace="http://www.mydata-control.de/4.0/mydataLanguage"
		schemaLocation="mydataLanguage.xsd" />
	<import namespace="http://www.mydata-control.de/4.0/event"
		schemaLocation="mydataEvent.xsd" />


	<complexType name="ValueChangedType">
		<attribute name="id" use="required">
			<simpleType>
				<restriction base="ID">
					<pattern
                            value="[a-f]{1}[a-f0-9]{7}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}">
					</pattern>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>


	<complexType name="ValueChangedBoolType">
		<complexContent>
			<extension base="tns:ValueChangedType">
				<sequence>
					<choice minOccurs="1" maxOccurs="1">
						<group ref="language:BooleanGroup" />
					</choice>
				</sequence>
				<attribute name="to" type="boolean" use="optional" />
			</extension>
		</complexContent>
	</complexType>

	<complexType name="ValueChangedStringType">
		<complexContent>
			<extension base="tns:ValueChangedType">
				<sequence>
					<choice minOccurs="1" maxOccurs="1">
						<group ref="language:StringGroup" />
					</choice>
				</sequence>
				<attribute name="to" type="string" use="optional" />
			</extension>
		</complexContent>
	</complexType>

	<complexType name="ValueChangedNumberType">
		<complexContent>
			<extension base="tns:ValueChangedType">
				<sequence>
					<choice minOccurs="1" maxOccurs="1">
						<group ref="language:NumberGroup" />
					</choice>
				</sequence>
				<attribute name="to" type="decimal" use="optional" />
			</extension>
		</complexContent>
	</complexType>

	<complexType name="ValueChangedListType">
		<complexContent>
			<extension base="tns:ValueChangedType">
				<sequence>
					<choice minOccurs="1" maxOccurs="1">
						<element ref="pip:list" />
						<element ref="event:list" />
						<element ref="constant:list" />
					</choice>
				</sequence>
			</extension>
		</complexContent>
	</complexType>


	<complexType name="ValueChangedObjectType">
		<complexContent>
			<extension base="tns:ValueChangedType">
				<sequence>
					<choice minOccurs="1" maxOccurs="1">
						<element ref="pip:object" />
						<element ref="event:object" />
						<element ref="constant:object" />
					</choice>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<element name="boolean" type="tns:ValueChangedBoolType" />
	<element name="string" type="tns:ValueChangedStringType" />
	<element name="number" type="tns:ValueChangedNumberType" />
	<element name="object" type="tns:ValueChangedObjectType" />
	<element name="list" type="tns:ValueChangedListType" />

	<group name="ValueChangedGroup">
		<choice>
			<element ref="tns:string" />
			<element ref="tns:number" />
			<element ref="tns:boolean" />
			<element ref="tns:object" />
			<element ref="tns:list" />
		</choice>
	</group>




</schema>


