name: GitHub Pages Check

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: read

jobs:
  build:
    name: Check GitHub Pages

    uses: ./.github/workflows/_gh-pages-build.yml
    with:
      upload-artifact: false
